language: node_js
node_js: "8"
script:
    - yarn run build:prod
sudo: false

deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
        branch: deploy
    local_dir: dist

cache:
    yarn: true
    directories:
        - node_modules

notifications:
    email: false
